# 여러 테이블 조합
/*
SELECT *
FROM TABLE_A
LEFT JOIN TABLE_B
ON TALBE_A.COLUMN1 = TABLE_B.COLUMN2
WHERE B.COLUMN3 = 'STR'
*/
# LEFT JOIN
# ORDERS를 A, CUSTOMERS를 B라는 테이블명으로 선언하고
# 그 중 ORDERNUMBER와 COUNTRY를 각각 가져와
# CUSTOMERNUMBER가 같은 것끼리 결합
# A기준으로 새로운 표가 생성되며 B에 값이 없으면 NULL 반환
SELECT A.ORDERNUMBER, B.COUNTRY
FROM classicmodels.ORDERS A
LEFT
JOIN classicmodels.CUSTOMERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER;

# WHERE로 조건을 줌
SELECT A.ORDERNUMBER, B.COUNTRY
FROM CLASSICMODELS.ORDERS A
LEFT
JOIN CLASSICMODELS.CUSTOMERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER
WHERE B.COUNTRY = 'USA';

# INNER JOIN : 공통으로 존재하는 데이터만 출력
SELECT A.ORDERNUMBER, B.COUNTRY
FROM CLASSICMODELS.ORDERS A
INNER
JOIN CLASSICMODELS.CUSTOMERS B
ON A.CUSTOMERNUMBER = B.CUSTOMERNUMBER
WHERE B.COUNTRY = 'USA';

# FULL JOIN : 모든 데이터를 출력