# GROUP BY : SUM, AVG, COUNT 같은 함수와 함께 사용
SELECT COUNTRY, CITY,
COUNT(CUSTOMERNUMBER) N_CUSTOMER
FROM classicmodels.customers
GROUP BY COUNTRY, CITY;

/* CASE WHEN (조건) THEN () ELSE () END : python의 if문과 비슷 */
SELECT SUM(CASE WHEN COUNTRY = 'USA' THEN 1 ELSE 0 END) N_USA,
SUM(CASE WHEN COUNTRY = 'USA' THEN 1 ELSE 0 END) / COUNT(*) USA_PORTION
# * 대신 COUNTRY를 넣어도 됨
FROM CLASSICMODELS.CUSTOMERS;