# RANK : 동점을 같은 등수, 다음 등수는 앞선 등수의 수만큼 밀림
# DENSE_RANK : 동점을 같은 등수, 다음 등수는 +1
# ROW_NUMBER : 동점을 다른 등수
SELECT BUYPRICE,
ROW_NUMBER() OVER(order by BUYPRICE) ROWNUMBER,
RANK() OVER(ORDER BY BUYPRICE) RNK,
DENSE_RANK() OVER(order by BUYPRICE) DENSERNK
FROM CLASSICMODELS.PRODUCTS;

# PARTITION BY : 그룹 생성을 하여 그룹별로 등수 매기기
SELECT BUYPRICE,
ROW_NUMBER() OVER(partition by PRODUCTLINE order by BUYPRICE) ROWNUMBER,
RANK() OVER(partition by PRODUCTLINE ORDER BY BUYPRICE) RNK,
DENSE_RANK() OVER(partition by PRODUCTLINE order by BUYPRICE) DENSERNK
FROM CLASSICMODELS.PRODUCTS;